---
repos:
  # Formats import order
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black", "--filter-files"]

  #Code formatter for both python files and jupyter notebooks
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        language_version: python3.10

  # remove unused imports
  - repo: https://github.com/hadialqattan/pycln.git
    rev: v2.1.3
    hooks:
      - id: pycln

  # additional hooks found with in the pre-commit lib
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace # removes trailing white spaces
      - id: mixed-line-ending # removes mixed end of line
        args:
          - --fix=lf
      - id: pretty-format-json # JSON Formatter
        args:
          - --autofix
          - --indent=4
          - --no-sort-keys
